#! /usr/bin/env bash
set -euo pipefail

configDir=${ACM_CONFIG_PATH:-~/.config/acm}
inputsFile="$configDir/inputs.txt"
outputsFile="$configDir/outputs.txt"

function getDevices() {
  readarray -t devices < <(aconnect -i -o | grep -v '^client 0' | grep -v '^client 14' | grep '^client')
}

function selectDevice() {
    file=$1
    readarray -t names < <(printf '%s\n' "${devices[@]}" | awk -F"'" '{print $2}')
    names+=(Cancel)
    PS3='Select Input: '
    select dev in "${names[@]}"; do
    case $dev in
    "Cancel")
        break
        ;;
    *)
        device="${devices[$((REPLY-1))]}"
        echo "device = $device"
        if [ ! -f "$file" ]; then
            mkdir -p "$(dirname "$file")"
        fi
        echo "$device" >> "$file"
        break
        ;;
    esac
    done
}

function doMenu() {
    PS3='Configure auto-connect-midi: '
    options=("Add Inputs" "Add Outputs" "Show Config" "Clear Config" "Connect Now" "Done")
    select opt in "${options[@]}"; do
    case $opt in
    "Add Inputs")
        getDevices
        selectDevice "$inputsFile"
        break
        ;;
    "Add Outputs")
        getDevices
        selectDevice "$outputsFile"
        break
        ;;
    "Show Config")
        echo "Inputs:"
        [ -f "$inputsFile" ] && cat "$inputsFile"
        echo "Outputs:"
        [ -f "$outputsFile" ] && cat "$outputsFile"
        break
        ;;
    "Clear Config")
        [ -f "$inputsFile" ] && rm "$inputsFile"
        [ -f "$outputsFile" ] && rm "$outputsFile"
        break
        ;;
    "Connect Now")
        ./auto-connect-midi
        break
        ;;
    "Done")
        exit 0
        ;;
    *)
        echo "Unknown Command $REPLY"
        break
        ;;
    esac
    done
}

while true; do
  doMenu
done

