#! /usr/bin/env bash
set -euo pipefail

configDir=${ACM_CONFIG_PATH:-~/.config/acm}
inputsFile="$configDir/inputs.txt"
outputsFile="$configDir/outputs.txt"

if [ ! -f "$inputsFile" ]; then
  echo "Inputs not found at $inputsFile" 1>&2
  exit 1
fi

if [ ! -f "$outputsFile" ]; then
  echo "Outputs not found at $outputsFile" 1>&2
  exit 1
fi

readarray -t inputs < <(cat $inputsFile | grep -v "^$")
readarray -t outputs < <(cat $outputsFile | grep -v "^$")
for input in "${inputs[@]}"; do
  inClient=$(awk '{print $2}' <<< "$input" | sed s/://g)
  for output in "${outputs[@]}"; do
    outClient=$(awk '{print $2}' <<< "$output" | sed s/://g)
    echo aconnect "$inClient":0 "$outClient":0
    aconnect "$inClient":0 "$outClient":0
  done
done

